import { UserPost, UserCommunityPost } from '../../models';

export const UserPosts: UserPost[] = [
  {
    id: '9',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '5m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'swap-option-included',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform!',
      messageTag: 'APT',
      collectionName: '',
      logo: '',
      price: 8.46,
    },
  },
  {
    id: '111',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'repost',
    content: {
      contentTypeOfRepost: 'message only',
      message: 'Just joined TowneSquare, a new web3 social platform!',
    },
  },
  {
    id: '7',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '1d',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'nft-for-sale',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      price: 100,
      collectionPFP: '',
      collectionName: 'Aptomingos',
      collectionId: '#9280',
    },
  },
  {
    id: '1',
    pfp: '',
    username: 'Real JC',
    nickname: 'Real',
    timepost: '6d',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'message only',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform!',
    },
  },

  {
    id: '2',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2h',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'messageImage',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '10',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '13h',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'floor-price',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform!',
      messageTag: 'AptosMonkeys',
      collectionName: 'Aptos Monkeys',
      amount: 14,
    },
  },
  {
    id: '44',
    pfp: '',
    username: 'Real JC',
    nickname: 'jczhang',
    timepost: '5m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'gif',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },

  {
    id: '5',
    pfp: '',
    username: 'Real JC',
    nickname: 'jczhang',
    timepost: '12h',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'video',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '6',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '7d',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'message-external-link',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      link: 'https://aptos.com/121907/building-aptos-theres-new-web3-accelerator',
      linkDescription: 'Aptos Autumn is Here',
      url: 'www.aptos.com',
      linkSubTitle:
        'Membership eaWe welcome everyone to participate in this movemen aime...',
    },
  },
  {
    id: '8',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '23h',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'attached-nft',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      price: 100,
      collectionPFP: '',
      collectionName: 'Aptomingos',
      collectionId: '#9280',
    },
  },
  // {
  //   id: '7',
  //   pfp: '',
  //   username: 'Username',
  //   nickname: 'username',
  //   timepost: '1d',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'nft-for-sale',
  //   content: {
  //     message: 'Just joined TowneSquare, a new web3 social platform',
  //     price: 100,
  //     collectionPFP: '',
  //     collectionName: 'Aptomingos',
  //     collectionId: '#9280',
  //   },
  // },
  // {
  //   id: '23',
  //   pfp: '',
  //   username: 'Real JC',
  //   nickname: 'jczhang',
  //   timepost: '25 Dec 22',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'repost',
  //   content: {
  //     contentTypeOfRepost: 'messageImage',
  //     message: 'Just joined TowneSquare, a new web3 social platform',
  //   },
  // },
  // {
  //   id: '3',
  //   pfp: '',
  //   username: 'Real JC',
  //   nickname: 'jczhang',
  //   timepost: '12h',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'message-Image',
  //   content: {
  //     message: 'Just joined TowneSquare, a new web3 social platform',
  //   },
  // },
  // {
  //   id: '4',
  //   pfp: '',
  //   username: 'Username',
  //   nickname: 'username',
  //   timepost: '1 Jan 22',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'repost',
  //   content: {
  //     contentTypeOfRepost: 'gif',
  //     message: 'Just joined TowneSquare, a new web3 social platform',
  //   },
  // },

  // {
  //   id: '55',
  //   pfp: '',
  //   username: 'Real JC',
  //   nickname: 'jczhang',
  //   timepost: '1h',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'repost',
  //   content: {
  //     contentTypeOfRepost: 'video',
  //     message: 'Just joined TowneSquare, a new web3 social platform',
  //   },
  // },

  // {
  //   id: '77',
  //   pfp: '',
  //   username: 'Username',
  //   nickname: 'username',
  //   timepost: '01 Sep 22',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'repost',
  //   content: {
  //     contentTypeOfRepost: 'nft-for-sale',
  //     message: 'Just joined TowneSquare, a new web3 social platform',
  //     price: 100,
  //     collectionPFP: '',
  //     collectionName: 'Aptomingos',
  //     collectionId: '#9280',
  //   },
  // },
  // {
  //   id: '8',
  //   pfp: '',
  //   username: 'Username',
  //   nickname: 'username',
  //   timepost: '23h',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'attached-nft',
  //   content: {
  //     message: 'Just joined TowneSquare, a new web3 social platform',
  //     price: 100,
  //     collectionPFP: '',
  //     collectionName: 'Aptomingos',
  //     collectionId: '#9280',
  //   },
  // },
  // {
  //   id: '88',
  //   pfp: '',
  //   username: 'Username',
  //   nickname: 'username',
  //   timepost: '3d',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'repost',
  //   content: {
  //     contentTypeOfRepost: 'attached-nft',
  //     message: 'Just joined TowneSquare, a new web3 social platform',
  //     price: 100,
  //     collectionPFP: '',
  //     collectionName: 'Aptomingos',
  //     collectionId: '#9280',
  //   },
  // },

  // {
  //   id: '99',
  //   pfp: '',
  //   username: 'Username',
  //   nickname: 'username',
  //   timepost: '6d',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'repost',
  //   content: {
  //     contentTypeOfRepost: 'swap-option-included',
  //     message: 'Just joined TowneSquare, a new web3 social platform!',
  //     messageTag: 'APT',
  //     collectionName: '',
  //     logo: '',
  //     price: 8.46,
  //   },
  // },

  // {
  //   id: '100',
  //   pfp: '',
  //   username: 'Username',
  //   nickname: 'username',
  //   timepost: '2d',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'repost',
  //   content: {
  //     contentTypeOfRepost: 'floor-price',
  //     message: 'Just joined TowneSquare, a new web3 social platform!',
  //     messageTag: 'AptosMonkeys',
  //     collectionName: 'Aptos Monkeys',
  //     amount: 14,
  //   },
  // },
  // {
  //   id: '11',
  //   pfp: '',
  //   username: 'Username',
  //   nickname: 'username',
  //   timepost: '30m',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'attached-nft',
  //   content: {
  //     message: 'Just joined TowneSquare, a new web3 social platform',
  //     price: 100,
  //     collectionPFP: '',
  //     collectionName: 'Aptomingos',
  //     collectionId: '#9280',
  //   },
  // },
  // {
  //   id: '12',
  //   pfp: '',
  //   username: 'Username',
  //   nickname: 'username',
  //   timepost: '25m',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'message-external-link',
  //   content: {
  //     message: 'Just joined TowneSquare, a new web3 social platform',
  //     link: 'https://aptos.com/121907/building-aptos-theres-new-web3-accelerator',
  //     linkDescription: 'Aptos Autumn is Here',
  //     url: 'www.aptos.com',
  //     linkSubTitle:
  //       'Membership eaWe welcome everyone to participate in this movemen aime...',
  //   },
  // },
  // {
  //   id: '123',
  //   pfp: '',
  //   username: 'Username',
  //   nickname: 'username',
  //   timepost: '5 Dec 22',
  //   comments: '99k',
  //   retweet: '99k',
  //   like: '99k',
  //   type: 'repost',
  //   content: {
  //     contentTypeOfRepost: 'message-external-link',
  //     message: 'Just joined TowneSquare, a new web3 social platform',
  //     link: 'https://aptos.com/121907/building-aptos-theres-new-web3-accelerator',
  //     linkDescription: 'Aptos Autumn is Here',
  //     url: 'www.aptos.com',
  //     linkSubTitle:
  //       'Membership eaWe welcome everyone to participate in this movemen aime...',
  //   },
  // },
];
export const CommunityPost: UserCommunityPost[] = [
  {
    id: '1',
    pfp: '',
    username: 'Real JC',
    nickname: 'jczhang',
    timepost: 'Just now',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'message only',
    postedin: 'Aptos Monkeys',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '2',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '1m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'messageImage',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '3',
    pfp: '',
    username: 'Real JC',
    nickname: 'jczhang',
    timepost: '5m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Show thread',
    type: 'messageImage',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '4',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '10m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'gif',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '5',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '25m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'video',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '6',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '30m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'message-external-link',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      link: 'https://aptos.com/121907/building-aptos-theres-new-web3-accelerator',
      linkDescription: 'Aptos Autumn is Here',
      url: 'www.aptos.com',
      linkSubTitle:
        'Membership eaWe welcome everyone to participate in this movemen aime...',
    },
  },
  {
    id: '7',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '59m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'nft-for-sale',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      price: 100,
      collectionPFP: '',
      collectionName: 'Aptomingos',
      collectionId: '#9280',
    },
  },
  {
    id: '8',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '1h',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'attached-nft',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      price: 100,
      collectionPFP: '',
      collectionName: 'Aptomingos',
      collectionId: '#9280',
    },
  },
  {
    id: '9',
    pfp: '',
    username: 'Real JC',
    nickname: 'jczhang',
    timepost: '23h',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'swap-option-included',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform!',
      messageTag: 'APT',
      collectionName: '',
      logo: '',
      price: 8.46,
    },
  },
  {
    id: '10',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '1d',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'floor-price',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform!',
      messageTag: 'AptosMonkeys',
      collectionName: 'Aptos Monkeys',
      amount: 14,
    },
  },
  {
    id: '11',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '6d',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'attached-nft',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      price: 100,
      collectionPFP: '',
      collectionName: 'Aptomingos',
      collectionId: '#9280',
    },
  },
  {
    id: '12',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2 Jun',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'message-external-link',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      link: 'https://aptos.com/121907/building-aptos-theres-new-web3-accelerator',
      linkDescription: 'Aptos Autumn is Here',
      url: 'www.aptos.com',
      linkSubTitle:
        'Membership eaWe welcome everyone to participate in this movemen aime...',
    },
  },
];
