import { UserPost, FeedContent, UserCommunityPost } from '../../models';

export const UserPosts: UserPost[] = [
  {
    id: '1',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '6d ',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'message only',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '2',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'messageImage',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '3',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'message-Image',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '4',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '25 Dec 22',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'gif',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '5',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '12h',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'video',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '6',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '1 Jan 22',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'message-external-link',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      link: 'https://aptos.com/121907/building-aptos-theres-new-web3-accelerator',
      linkDescription: 'Aptos Autumn is Here',
      url: 'www.aptos.com',
      linkSubTitle:
        'Membership eaWe welcome everyone to participate in this movemen aime...',
    },
  },
  {
    id: '7',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '5m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'nft-for-sale',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      price: 100,
      collectionPFP: '',
      collectionName: 'Aptomingos',
      collectionId: '#9280',
    },
  },
  {
    id: '8',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '5m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'attached-nft',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      price: 100,
      collectionPFP: '',
      collectionName: 'Aptomingos',
      collectionId: '#9280',
    },
  },
  {
    id: '9',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '15 May',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'swap-option-included',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform!',
      messageTag: 'APT',
      collectionName: '',
      logo: '',
      price: 8.46,
    },
  },
  {
    id: '10',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '5m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'floor-price',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform!',
      messageTag: 'AptosMonkeys',
      collectionName: 'Aptos Monkeys',
      amount: 14,
    },
  },
  {
    id: '11',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '16 Jun 22',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'attached-nft',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      price: 100,
      collectionPFP: '',
      collectionName: 'Aptomingos',
      collectionId: '#9280',
    },
  },
  {
    id: '12',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '5m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'message-external-link',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      link: 'https://aptos.com/121907/building-aptos-theres-new-web3-accelerator',
      linkDescription: 'Aptos Autumn is Here',
      url: 'www.aptos.com',
      linkSubTitle:
        'Membership eaWe welcome everyone to participate in this movemen aime...',
    },
  },
];
export const CommunityPost: UserCommunityPost[] = [
  {
    id: '1',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    type: 'message only',
    postedin: 'Aptos Monkeys',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '2',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'messageImage',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '3',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '22h',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Show thread',
    type: 'messageImage',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '4',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'gif',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '5',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'video',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
    },
  },
  {
    id: '6',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '5d',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'message-external-link',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      link: 'https://aptos.com/121907/building-aptos-theres-new-web3-accelerator',
      linkDescription: 'Aptos Autumn is Here',
      url: 'www.aptos.com',
      linkSubTitle:
        'Membership eaWe welcome everyone to participate in this movemen aime...',
    },
  },
  {
    id: '7',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'nft-for-sale',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      price: 100,
      collectionPFP: '',
      collectionName: 'Aptomingos',
      collectionId: '#9280',
    },
  },
  {
    id: '8',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '16 Nov 22',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'attached-nft',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      price: 100,
      collectionPFP: '',
      collectionName: 'Aptomingos',
      collectionId: '#9280',
    },
  },
  {
    id: '9',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '16 Jun',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'swap-option-included',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform!',
      messageTag: 'APT',
      collectionName: '',
      logo: '',
      price: 8.46,
    },
  },
  {
    id: '10',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'floor-price',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform!',
      messageTag: 'AptosMonkeys',
      collectionName: 'Aptos Monkeys',
      amount: 14,
    },
  },
  {
    id: '11',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '2m',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'attached-nft',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      price: 100,
      collectionPFP: '',
      collectionName: 'Aptomingos',
      collectionId: '#9280',
    },
  },
  {
    id: '12',
    pfp: '',
    username: 'Username',
    nickname: 'username',
    timepost: '01 Apr',
    comments: '99k',
    retweet: '99k',
    like: '99k',
    postedin: 'Aptos Monkeys',
    type: 'message-external-link',
    content: {
      message: 'Just joined TowneSquare, a new web3 social platform',
      link: 'https://aptos.com/121907/building-aptos-theres-new-web3-accelerator',
      linkDescription: 'Aptos Autumn is Here',
      url: 'www.aptos.com',
      linkSubTitle:
        'Membership eaWe welcome everyone to participate in this movemen aime...',
    },
  },
];
